// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using MassTransit.EntityFrameworkCoreIntegration;
using Microsoft.EntityFrameworkCore;
using Saga.Domain.Entities;
using Saga.Domain.Maps;

#nullable disable

namespace Saga.Infrastructure;

public partial class SagaContext : SagaDbContext
{
    public SagaContext(DbContextOptions<SagaContext> options)
        : base(options)
    {
    }

    public virtual DbSet<TicketState> TicketStates { get; set; }

    protected override IEnumerable<ISagaClassMap> Configurations
    {
        get
        {
            yield return new TicketStateMap();
        }
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.ApplyConfiguration(new Configurations.TicketStateConfiguration());

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}
