// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Audit.Domain.Entities;
using Microsoft.EntityFrameworkCore;
#nullable disable

namespace Audit.Infrastructure;

public partial class AuditContext : DbContext
{
    public AuditContext(DbContextOptions<AuditContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Log> Logs { get; set; }

    public virtual DbSet<Status> Statuses { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.ApplyConfiguration(new Configurations.LogConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.StatusConfiguration());

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}
