// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using MassTransit;
using Microsoft.EntityFrameworkCore;

namespace Saga.Domain.Entities;

[Table("TicketOrderState")]
public partial class TicketOrderState : SagaStateMachineInstance
{
    [Key]
    public Guid CorrelationId { get; set; }

    [Required]
    [StringLength(50)]
    public string CurrentState { get; set; }

    public Guid TheaterId { get; set; }

    public Guid MovieId { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime Showtime { get; set; }

    [Column(TypeName = "xml")]
    public string Seats { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime LastUpdatedDate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreationDate { get; set; }
}