// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Automatonymous;
using MassTransit;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Saga.Domain.Entities;

[Table("TicketState")]
public partial class TicketState : SagaStateMachineInstance
{
    [Key]
    public Guid CorrelationId { get; set; }

    [Required]
    [StringLength(50)]
    public string CurrentState { get; set; }

    public DateTime? LastUpdatedDate { get; set; }
}