// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Audit.Domain.Base;
using System;
using System.Collections.Generic;

namespace Audit.Domain.Entities;

public partial class Log : Entity
{
    public int StatusId { get; set; }

    public Guid CorrelationId { get; set; }

    public string Message { get; set; }

    public DateTime? Timestamp { get; set; }

    public string CreatedBy { get; set; }

    public virtual Status Status { get; set; }
}