// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Audit.Domain.Base;
using System;
using System.Collections.Generic;

namespace Audit.Domain.Entities;

public partial class Status : Entity
{
    public string Status1 { get; set; }

    public virtual ICollection<Log> Logs { get; set; } = new List<Log>();
}